### PR TITLE
Several small enhancements and bugfixes

### PR DESCRIPTION
**Pull request by dankarp**
* On redirect, PROPFIND depth was always being reset to "1". This change maintains the Depth header through HTTP redirect.
* Adds support for Bearer authorization with a new `SardineImpl` constructor
* Exposes *resourcetype* attribute on `DavResource`
* Supports Depth: infinite on PROPFIND via negative values of depth parameter
* Adds a new `Sardine.propfind` method that acts as a `list` without fetching default props

### CODE REVIEW

**Comment by lookfirst** [comment]
:+1: from me. Some of the formatting is a bit inconsistent (braces on weird lines) but shrug... ok... probably we should go through and worry about that in a different commit across the whole codebase.

@dkocher ?

**Comment by dankarp** [comment]
Sorry about the weird braces. I'm actually a K&R C/standard Java believer, but I was trying to match the style of the source files. If you guys would rather go with the [Java standard](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-142311.html#449) for braces, I'd be glad to do all further pull requests in that idiom.

**Comment by dkocher** [comment]
I agree we should fix formatting for the entire project in a separate pull request.

**Comment by lookfirst** [comment]
@dkocher You good with this PR?

**Pull request merged**
