### PR TITLE
Upgrade to Jakarta EE 10 / Jakarta XML Bind 4.0

### PR DESCRIPTION
**Pull request by RickardNarsromLINK**
Upgrade Jakarta XML Bind to version 4.0. Including changing the package name from javax to jakarta.

Also include Jakarta XML Bind runtime as a runtime dependency as this is required for Sardine to function and for unit tests to execute successful.

### CODE REVIEW

**Comment by lookfirst** [comment]
Here we are, 13 years later, still getting PR's. Thanks @RickardNarsromLINK !

**Comment by lookfirst** [comment]
@dkocher We should probably do a v6.0?

**Comment by dkocher** [comment]
> @dkocher We should probably do a v6.0?

I have no objection.

**Comment by dkocher** [comment]
> Hi, thanks for the great work on this library. Any chance to see a release soonish? Using this library in Spring Boot 3 now requires a version with this PR merged.

A new [release](https://github.com/lookfirst/sardine/releases) has now been pushed and is available in [Maven Central](https://central.sonatype.com/artifact/com.github.lookfirst/sardine/5.12/versions).

**Comment by glmxndr** [comment]
You are fantastic people. Thanks a bunch.

**Pull request merged**
