### PR TITLE
Do not read to the end of the entity when closing input stream before…

### PR DESCRIPTION
**Pull request by dkocher**
… reaching the content length.

### CODE REVIEW

**Comment by lookfirst** [comment]
I wish there was an easy way to get travis to re-run the tests?

**Comment by dkocher** [comment]
@lookfirst By updating the pull request or choosing the upper right _Reload_ button on the travis page.

**Comment by dkocher** [comment]
@lookfirst Please wait merging this.

**Comment by dkocher** [comment]
However what I want to achieve here is that closing a stream is possible without waiting for the potentially long I/O to finish. A caller might decide to close the stream before reaching the end but then would not want to wait for the server to send all remaining content.

**Comment by lookfirst** [comment]
Oh cool. No worries, I'm not touching anything. Too busy with day job these days. =)

**Pull request merged**
