### PR TITLE
added support for WebDAV REPORT method

### PR DESCRIPTION
**Pull request by dankarp**
Added Sardine.report(), which composes and executes a WebDAV REPORT request on the passed-in report object.  These report objects must implement com.github.sardine.report.SardineReport, an abstract class which defines a marshal-to-JAXB-object method and a unmarshal-from-Multistatus method.  (The unmarshal method returns a report-specific object that we declared as the parameterized generic type when we implemented SardineReport.)  One report (SyncCollectionReport) is declared in webdav.xsd and in the report package, but it should be straightforward to add more.

Simplified DavResource tests using a fluent Builder with sane defaults.

### CODE REVIEW

**Comment by lookfirst** [comment]
@dkocher I vote that we give @dankarp commit access. He's doing a wonderful job.

**Comment by dkocher** [comment]
+1

**Comment by lookfirst** [comment]
@dankarp Welcome to the club. I just added you as a committer. I just ask that you continue the path of submitting PR's and getting thumbs up on them. But, now you have the final ability to merge yourself. =) Thanks for your excellent contributions.

**Comment by dankarp** [comment]
It's an honor and a privilege.

**Pull request merged**
