### PR TITLE
Integrate testcontainers

### PR DESCRIPTION
**Pull request by LotharSpiegel**
Proposition to resolve https://github.com/lookfirst/sardine/issues/261 (missing test setup) by using the [testcontainers Java library](https://www.testcontainers.org/). The proposed solution spins up a WebDAV server inside a Docker container during tests. By using this approach, the test setup becomes independent from external resources, as opposed to using a publicly hosted WebDAV server.

### CODE REVIEW

**Comment by dkocher** [comment]
It should then be possible to no longer exclude the tests marked with `@IntegrationTest` [^1].

[^1]: https://github.com/lookfirst/sardine/blob/master/pom.xml#L107

**Comment by dkocher** [comment]
> It should then be possible to no longer exclude the tests marked with `@IntegrationTest` [1](#user-content-fn-1-e7d6fe56e9efd1852194cdf7db911b18).
> 
> ## Footnotes
> 1. https://github.com/lookfirst/sardine/blob/master/pom.xml#L107 [↩](#user-content-fnref-1-e7d6fe56e9efd1852194cdf7db911b18)

@lookfirst Probably we should keep as is and run only unit tests in the surefire plugin?

**Comment by lookfirst** [comment]
> > It should then be possible to no longer exclude the tests marked with `@IntegrationTest` [1](#user-content-fn-1-e7d6fe56e9efd1852194cdf7db911b18).
> > ## Footnotes
> > 
> > 1. https://github.com/lookfirst/sardine/blob/master/pom.xml#L107 [↩](#user-content-fnref-1-e7d6fe56e9efd1852194cdf7db911b18)
> 
> @lookfirst Probably we should keep as is and run only unit tests in the surefire plugin?

I love this PR. Sounds good to only run unit tests in maven and then run integration tests in this PR.

**Comment by LotharSpiegel** [comment]
> > > It should then be possible to no longer exclude the tests marked with `@IntegrationTest` [1](#user-content-fn-1-e7d6fe56e9efd1852194cdf7db911b18).
> > > ## Footnotes
> > > 
> > > 1. https://github.com/lookfirst/sardine/blob/master/pom.xml#L107 [↩](#user-content-fnref-1-e7d6fe56e9efd1852194cdf7db911b18)
> > 
> > 
> > @lookfirst Probably we should keep as is and run only unit tests in the surefire plugin?
> 
> I love this PR. Sounds good to only run unit tests in maven and then run integration tests in this PR.

Thank you for reviewing! So do you mean to leave the exclusion of integration tests as is in the maven-surefire-plugin?  If I understand correctly, the integration tests are then executed in the maven-failsafe-plugin.

**Comment by dkocher** [comment]
@LotharSpiegel Do you have experience with testcontainers running in the context of Github Actions using Github-hosted runners? It [seems](https://github.com/lookfirst/sardine/actions/runs/5282987562/jobs/9558625413) there is no Docker environment available.

**Pull request merged**
