### PR TITLE
Enable tests. (Configuration fixed on server side)

### LINKED ISSUE #198: Tests failing
4 unit tests are failing:

testLockUnlock(com.github.sardine.LockTest): Unexpected response
testAddPropertyDefaultNamespace(com.github.sardine.ProppatchTest): Unexpected response
testRemovePropertyCustomNamespace(com.github.sardine.ProppatchTest): Unexpected response
testAddPropertyCustomNamespace(com.github.sardine.ProppatchTest): Unexpected response

They're probably linked to a change on http://sudo.ch/.

### PR DESCRIPTION
**Pull request by dkocher**
Fix #198.

### CODE REVIEW

**Comment by lookfirst** [comment]
@dkocher Would it be possible to setup tests against a (free) heroku dyno? That way, we can check the buildpack into github and not have to rely on a private server that only you have access to? I guess what I'd need in order to do this would be your configuration on your end. I can also move sardine over to a github organization so that we can host everything under an org too.

**Comment by dkocher** [comment]
+1. Below my current configuration (Apache HTTPD)

```
<VirtualHost *:80>
    ServerName test.cyberduck.ch
    ServerAlias test.cyberduck.io

    <IfModule mod_deflate.c>
	    SetOutputFilter DEFLATE
    </IfModule>

    <Location /dav>
        Deny from all
        RewriteEngine off
    </Location>

    <Location /dav/anon>
        Allow from all
        RewriteEngine off
        DAV on
        Options +Indexes
    </Location>

    <Location /dav/basic>
        Allow from all
        RewriteEngine Off
        DAV on
        # Limit just the DAV methods
        <Limit GET PUT POST DELETE PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK>
            AuthType Basic
            AuthName "DAV Access Basic"
            AuthUserFile basic.passwd
            Require valid-user
        </Limit>
    </Location>

    <Location /dav/digest>
        Allow from all
        RewriteEngine Off
        DAV on
        # Limit just the DAV methods
        <Limit GET PUT POST DELETE PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK>
        	AuthType Digest
        	AuthName "DAV Access Digest"
        	AuthUserFile digest.passwd
        	Require valid-user
        </Limit>
    </Location>
	
    RedirectMatch 301 ^/redir-perm/$ http://test.cyberduck.ch/dav/basic
    RedirectMatch 302 ^/redir-tmp/(.*)$ http://test.cyberduck.ch/dav/basic/$1
    RedirectMatch 303 ^/redir-other/$ http://test.cyberduck.ch/dav/basic
    RedirectMatch 410 ^/redir-gone/$
</VirtualHost>
```

**Comment by lookfirst** [comment]
Ok, this is going to be a pain... I need to build a custom buildpack on heroku for apache and sadly there isn't one that is recent, actually compiles apache (and cache's the output) and has webdav built in.

Will probably base it off something like this: https://github.com/lookfirst/heroku-buildpack-nginx

I'd use nginx, but the webdav support there is pretty limited.

**Comment by lookfirst** [comment]
Update. I've almost got the buildpack working...  https://github.com/lookfirst/heroku-buildpack-apache

**Comment by JialuZhang** [comment]
@lookfirst 

In your configuration,
```
    <Location /dav>
        Deny from all
        RewriteEngine off
    </Location>
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
Thanks!

**Pull request merged**
